### ISSUE TITLE
Port missing info about Logos from the devwiki

### ISSUE THREAD

**Issue by uroboro** [theos/theos.dev#11]
The previous [wiki page](https://iphonedev.wiki/index.php?title=Logos&oldid=5734) still has some bits of info not on this repo. Namely "Command line interface" and "Splitting Logos Hooking Code Across Multiple Files"

**Comment by kirb** [comment]
Should we keep those on dev wiki for the time being?

**Comment by uroboro** [comment]
I did the same to the Logos page as you did to the Theos/Setup: replaced with a soft redirect and a link to the last usable revision
