### ISSUE TITLE
`Depends: ${LIBSWIFT}` recommendation in docs is outdated

### ISSUE THREAD

**Issue by p0358** [theos/theos.dev#47]
It says this:
https://github.com/theos/theos.dev/blob/1dc23040c5b141334634d150b4cc963f7dc8f860/docs/Swift.md#L9

But Swift for some time is already bundled with iOS and the `${LIBSWIFT}` dependency isn't even installable on newer iOS (especially on rootless where it's just missing).

This PR was submitted for templates (theos/templates#32):
https://github.com/theos/templates/pull/32/commits/6d400f1e564c614de3f48888a205f6d4da747837

So I think that docs should also change
```
Depends: ${LIBSWIFT}
```
to
```
Depends: firmware (>= 12.2) | ${LIBSWIFT}
```
in that place.

**Comment by L1ghtmann** [comment]
Nice catch! Yeah, that statement should probably be updated. Feel free to pr a change.
